CXXFLAGS += -D NO_CAEN

$(BINDIR)/CAEN_%: 
	@echo $(call InfoLine , "NO CAEN WILL PLACE DUMMY FOR $@" )
	touch $@
$(BINDIR)/HwManager.o: 
	@echo $(call InfoLine , "NO CAEN WILL PLACE DUMMY FOR $@" )
	touch $@
$(BINDIR)/FSM.o: 
	@echo $(call InfoLine , "NO CAEN WILL PLACE DUMMY FOR $@" )
	touch $@
$(BINDIR)/Daemon.o: 
	@echo $(call InfoLine , "NO CAEN WILL PLACE DUMMY FOR $@" )
	touch $@

## REMOVE PACKAGES
## instruct to compile only the soLibrary
Packages=

all2: $(SoLib)



